[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
  from = “http://localhost:4000/*”
  to = “https://632766e69c51cc6838f771aa--coruscating-torte-94cbee.netlify.app/"
  status = 200